"""Base tables

Revision ID: 357984f69d41
Revises: 
Create Date: 2024-04-15 22:08:51.047114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357984f69d41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_m2m_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_recipe', sa.Integer(), nullable=True),
    sa.Column('id_ingredient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ingredient'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['id_recipe'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_m2m_ingredient')
    op.drop_table('recipes')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
